### ISSUE TITLE
Getting Incorrect file type

### ISSUE THREAD

**Issue by iamonuwa** [onfido/api-javascript-client#1]
Am building a verification system using Onfido with NodeJS.

After creating an applicant and running checks, I get incorrect file type anytime I am uploading a file using the uploadDocument method of this sdk. 
```
var applicant_id = req.body.applicant_id;

   var type = 'passport';
  var opts = {
	side: 'front',
	file: req.file.path
};
 console.log(opts['file']);
api.uploadDocument(applicant_id, type, opts, function (err, data, response) {
// console.log('Err', err);
// console.log('Data', data);
 console.log('Response', response);
})
```

Response Output
![image](https://user-images.githubusercontent.com/6551094/37334706-eb1ce19a-26ac-11e8-8247-5672e7e00370.png)

Please, what is the solution to this issue? 

Warm Regards,
Isaac.

**Comment by hjheath** [comment]
Hi Isaac, 

Sorry for the slow reply. The problem is that the `file` option should be a file like object rather than a string. If you try:
```
var opts = {
  side: 'front',
  file: req.file
};
```
I'm not sure what your file object is, but the following worked for me:
```
var fs = require('fs');
var data = fs.createReadStream( __dirname + '/image.png');
var opts = {
  side: 'front',
  file: data
};
```

**Comment by iamonuwa** [comment]
Alright, thank you
