### ISSUE TITLE
I can't use API in NodeJs project

### ISSUE THREAD

**Issue by richardfgb** [onfido/api-javascript-client#11]
I have created a new project with NodeJs and run '''npm install onfido''' but when I use '''const Onfido = require('onfido');''' I have the error "Module not found".

This error also appears in a new React project.

**Comment by ciaran16** [comment]
Hi @richardfgb, please note this library isn't supported on the front-end if you're trying to use this with React client-side.

If you're instead using this on the back-end and you're still having issues getting it to work, could you please email api@onfido.com to help you best. Thanks!
