### ISSUE TITLE
Upload a live video

### ISSUE THREAD

**Issue by DarynHolmes** [onfido/api-javascript-client#12]
Is it possible to use this library to upload an example live video?

The documentation only refers to documents, is there support for video?

Thanks

**Comment by ciaran16** [comment]
Hi @DarynHolmes, it's not possible to upload Live Videos via the API or the client libraries. Currently Live Videos are only uploaded by the SDKs, you can read more here: https://documentation.onfido.com/#live-videos

**Comment by vmachacek** [comment]
I need this feature for automated integration testing. The testing in on HTTP level, thus I can't orchestrate iOS or Android device to upload the video. Is there any way to do this?
