### ISSUE TITLE
Issue while downloading file from onfido using api endpoints as suggested in the document

### ISSUE THREAD

**Issue by ShrawanLakhe** [onfido/api-javascript-client#13]
I am trying to download the file from Node.js using api endpoints with this endpoint https://api.onfido.com/v2/applicants/{applicant_id}/documents/{document_id}/download
but rather than getting binary value of the file, i am getting content in xmp adobe format which is corrupting the downloaded files. how can i solve this issue. I have attached the file with the content that i am getting from the onfdio. Please suggest 
![kyc_doc_141982e4-be4c-4040-bd60-c9005c288138_front-passport-shrawan](https://user-images.githubusercontent.com/5616157/56658201-bb5e1980-66b9-11e9-8e61-95708e2142d9.png)

**Comment by ciaran16** [comment]
Hi @ShrawanLakhe, is this using the API endpoint directly or using this client library?

If you're making calls to the api endpoint directly, please could you email api@onfido.com who will be able to help you best.

If this is via this client library, there is currently a known issue with downloading, see more info here: https://github.com/onfido/api-javascript-client#uploading-and-downloading
