### ISSUE TITLE
Typescript integration?

### ISSUE THREAD

**Issue by menoude** [onfido/api-javascript-client#14]
Hi,

We intend to include Onfido in the onboarding process of our mobile app. We've received some API tokens and already started to fiddle with the tool. We would like to use your Javascript client library in our code in order to kick off the integration.

Our problem is that we're using NodeJs with Typescript, and that we can't find a `.d.ts` file that declare the types used in this library.

I know that the different client libraries were automatically generated through OpenAPIGenerator and that Typescript generation is [supported by their tool](https://openapi-generator.tech/docs/generators/typescript-node). Would it be possible to create a Typescript version of your api client? I hope that would be more reasonable than ask to actually write a `.d.ts` file for the pure Javascript client (I can tell you, I just tried :) )

Thank you!

**Comment by ciaran16** [comment]
Hi @menoude, thanks for your question.

I think you also emailed API support about this issue and they've responded, so I'm going to close this. If that's not the case or you have any other questions, feel free to re-open.

**Comment by Antonhansel** [comment]
Hello there,

I have the same question and I'm sure many others do, would you mind also answering here, so you don't have to answer future mails about this ;) ?

**Comment by robsonvn** [comment]
@ciaran16 could you tell us if there's any plan to implement the TS types?

**Comment by ciaran16** [comment]
Hi @robsonvn, This library has been superseded by [onfido/onfido-node](https://github.com/onfido/onfido-node) which is written in TypeScript and includes types. I recommend you use that if you're working on a new integration.
