### ISSUE TITLE
[BUG] CheckCreationRequest.reportTypeGroups is sending malformed data in body.

### ISSUE THREAD

**Issue by kochavi-daniel** [onfido/api-javascript-client#5]
What I'm trying to do is create a check using a report type group. 

I'm doing the following:

```
const checkCreationRequest = new onfido.CheckCreationRequest()
checkCreationRequest.type = 'standard'
checkCreationRequest.reportTypeGroups = [1234]

const opts = {
            data: checkCreationRequest
        }

api.createCheck(applicantId, opts, callback)
```

This fails on the server with:
```
{
  error: {
    type: 'validation_error',
    message: 'There was a validation error on this request',
    fields: {
      base: [
        Array
      ]
    }
  }
}
```

When I debug the code I see that the issue is the sdk sends the request body like this:
```
{
  "type": "standard",
  "reportTypeGroups": [1234]
}
```

When I change this line:
`checkCreationRequest.reportTypeGroups =[1234]`
to
`checkCreationRequest.report_type_groups =[1234]`

everything works.

**Comment by ciaran16** [comment]
Thanks for spotting this, the tool we used to generate this library was generating the code in snake_case and the documentation in camelCase. This is fixed in the latest version.
